# Generated by Django 3.1.7 on 2021-03-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('1', 'Operador de Maquinas Pesadas'), ('2', 'Administrativos'), ('3', 'Ajudante Geral')], max_length=5, verbose_name='Cargo do Trabalhador')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data de entrada')),
                ('valor_Total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('setor', models.CharField(choices=[('1', 'Agricultura'), ('2', 'Infraestrutura'), ('3', 'Saúde')], max_length=5, verbose_name='Setor de Trabalho')),
                ('telefone_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone_fixo', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=14, verbose_name='RG')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('cnh', models.CharField(max_length=13, verbose_name='CNH')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cargo')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descreva a máquina em detalhes, ex: modelo, marca, nome, etc.', max_length=50, verbose_name='Descrição')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano da Máquina')),
                ('horimetro', models.IntegerField(verbose_name='Horímetro')),
                ('prefixo', models.CharField(max_length=20)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
            options={
                'verbose_name': 'Máquina',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome ou descrição do produto.', max_length=50)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade_minima', models.IntegerField(help_text='Informe a quantidade mínima para gerar um alerta de estoque.', verbose_name='Quantidade mínima')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcionario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina')),
            ],
            options={
                'verbose_name': 'Data da retirada/saída',
            },
        ),
        migrations.CreateModel(
            name='Produtos_Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade retirada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.saida')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos_Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_Unitario', models.FloatField(verbose_name='Preço unitário')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.entrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=50, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=50, verbose_name='Nome Fantasia')),
                ('vendedor', models.CharField(max_length=50, verbose_name='Nome do vendedor')),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='URL do Site')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado'),
        ),
    ]
