# Generated by Django 2.2.12 on 2021-03-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Estado')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Maquina')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Maquina')),
                ('ano', models.CharField(max_length=50, verbose_name='Ano da Maquina')),
                ('horimetro', models.IntegerField(verbose_name='Horimetro')),
                ('prefixoMaquina', models.CharField(max_length=100, verbose_name='Prefixo')),
                ('idcid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Funcionario')),
                ('dataNascimento', models.DateField(verbose_name='Data Nascimento')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor de Trabalho')),
                ('telefoneCelular', models.IntegerField(verbose_name='TelefoneCelular')),
                ('telefoneFixo', models.IntegerField(verbose_name='TelefoneFixo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=9, verbose_name='RG')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('cnh', models.CharField(max_length=11, verbose_name='CNH')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('idcid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('nomedocontribuinte', models.CharField(max_length=50, verbose_name='Nome da Razão Social')),
                ('nome', models.CharField(max_length=50, verbose_name='Funcionario')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('telefoneCelular', models.IntegerField(verbose_name='TelefoneCelular')),
                ('telefoneFixo', models.IntegerField(verbose_name='TelefoneFixo')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='URL')),
                ('idcid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Cidade')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='idest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Estado'),
        ),
    ]
