# Generated by Django 2.2.12 on 2021-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Funcionario')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('telefoneCelular', models.IntegerField(blank=True, null=True, verbose_name='TelefoneCelular')),
                ('telefoneFixo', models.IntegerField(blank=True, null=True, verbose_name='TelefoneFixo')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
