# Generated by Django 3.1.7 on 2021-03-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('1', 'Operador de Maquinas Pesadas'), ('2', 'Administrativos'), ('3', 'Ajudante Geral')], max_length=5, verbose_name='Cargo do Trabalhador'),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
