# Generated by Django 2.2.12 on 2021-03-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210320_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVenda', models.DateField(verbose_name='Data da Venda')),
                ('idLoteProduto', models.IntegerField(max_length=50, verbose_name='Data da Venda')),
                ('precoTotal', models.IntegerField()),
                ('idform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRetirada', models.DateField(verbose_name='Data Retirada')),
                ('quatidadeRetirada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade Retirada')),
                ('idfuncionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Funcionario')),
                ('idmaquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.PrefixoMaquina')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('qtdeatual', models.IntegerField(verbose_name='Quantidade atual')),
                ('qtdemin', models.IntegerField(verbose_name='Quantidade minima')),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do Produto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Entrada')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Saida')),
            ],
        ),
        migrations.CreateModel(
            name='Itens_Mov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('idloteprod', models.IntegerField(verbose_name='Lote do produto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Entrada')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Saida')),
            ],
        ),
    ]
