# Generated by Django 3.1.5 on 2021-03-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210323_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='valor_Total',
        ),
        migrations.RemoveField(
            model_name='produtos_entrada',
            name='preco_Unitario',
        ),
        migrations.AddField(
            model_name='entrada',
            name='detalhes',
            field=models.CharField(default='Teste', help_text='Informe mais detalhes da entrada, como NF, Nº do Pedido, etc.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos_entrada',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Preço unitário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='detalhes',
            field=models.CharField(default='Teste de saída', help_text='Informe mais detalhes da saída, Nº do Pedido, Ordem de serviço, etc.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=2, help_text='Essa quantidade vai ser atualizada pelo movimento de entrada e saída.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='saida',
            name='funcionario',
            field=models.ForeignKey(help_text='Informe o funcionário que fez esta solicitação de saída.', on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcionario'),
        ),
    ]
