# Generated by Django 3.1.7 on 2021-03-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20210324_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name': 'Movimentação da entrada'},
        ),
        migrations.AlterModelOptions(
            name='saida',
            options={'verbose_name': 'Movimentação de retirada/saída'},
        ),
        migrations.AlterField(
            model_name='maquina',
            name='prefixo',
            field=models.CharField(help_text='Identificação da máquina, placa, número, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='saida',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina', verbose_name='máquina'),
        ),
    ]
