# Generated by Django 3.1.5 on 2021-03-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20210329_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='detalhes',
            field=models.CharField(help_text='Informe mais detalhes da saída, Nº do Pedido, Ordem de serviço, etc.', max_length=100),
        ),
        migrations.CreateModel(
            name='Controle_Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_horimetro', models.IntegerField(verbose_name='Último Horimetro')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.maquina')),
            ],
            options={
                'verbose_name': 'Máquina',
            },
        ),
    ]
