# Generated by Django 2.2.16 on 2021-03-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20210329_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saida',
            options={'ordering': ['-pk'], 'verbose_name': 'Movimentação de retirada/saída'},
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.IntegerField(blank=True, default=0, help_text='Informe a validade em horas, caso tenha.'),
        ),
        migrations.AddField(
            model_name='saida',
            name='horimetro',
            field=models.IntegerField(default=0, help_text='Informe o horímetro atual da máquina.', verbose_name='Horímetro'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horimetro_revisao', models.IntegerField()),
                ('feita', models.BooleanField(default=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Maquina')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Produto')),
            ],
        ),
    ]
