# Generated by Django 3.1.7 on 2021-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20210330_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'ordering': ['-pk'], 'verbose_name': 'Movimentação da entrada'},
        ),
        migrations.AlterModelOptions(
            name='revisao',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='site',
            field=models.CharField(blank=True, default='http://', max_length=50, null=True, verbose_name='URL do Site'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('Operador de Maquinas Pesadas', 'Operador de Maquinas Pesadas'), ('Administrativos', 'Administrativos'), ('Ajudante Geral', 'Ajudante Geral')], max_length=100, verbose_name='Cargo do Trabalhador'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('Agricultura', 'Agricultura'), ('Infraestrutura', 'Infraestrutura'), ('Saúde', 'Saúde')], max_length=100, verbose_name='Setor de Trabalho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Essa quantidade vai ser atualizada pelo movimento de entrada e saída.', max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Controle_Maquina',
        ),
    ]
