# Generated by Django 3.1.7 on 2021-04-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20210403_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Essa quantidade vai ser atualizada pelo movimento de entrada e saída.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_minima',
            field=models.IntegerField(blank=True, default=1, help_text='Informe a quantidade mínima para gerar um alerta de estoque.', verbose_name='Quantidade mínima'),
        ),
    ]
